name: Run Tests Twice Daily

on:
  schedule:
    - cron: '0 0,12 * * *'  # midnight and noon

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      env:
        VIKIT_API_TOKEN: ${{ secrets.VIKIT_API_TOKEN }}
      run: |
          pytest -s tests/test_ci_providers_health_checks.py::TestProvidersHealthChecks::test_stabilityai_provider_and_generate
          pytest -s tests/test_ci_providers_health_checks.py::TestProvidersHealthChecks::test_videocrafter_provider_and_generate
          pytest -s tests/test_ci_providers_health_checks.py::TestProvidersHealthChecks::test_haiper_provider_and_generate